disabled_rules: # rule identifiers to exclude from running
  - operator_whitespace
  - identifier_name
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - control_statement
  - function_body_length
  - function_parameter_count
  - type_body_length
  - file_length
  - implicit_getter
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try: warning